### PR TITLE
Refactored code in several files for better readability

### PR DESCRIPTION
**Pull request by TarikKaanKoc**
I'll edit again later.

### CODE REVIEW

**Comment by Joao-L-S-Almeida** [comment]
I have some minor questions:
* Is it  already  confirmed the massive renaming did not provoked breaks in the sanity checks in `tests` ?
* Is it already confirmed the renaming also did not mess up the examples in `examples` ?
* Is the renaming affecting the packaging process, since we have now simulai and not src/simulai as root ?

**Comment by TarikKaanKoc** [comment]
That is correct. The imports in the test script are relative to the simulai package and it is located inside the ``"src"`` directory. Since the package directory is being renamed, the import statements in the test script will no longer be able to find the simulai package and will result in the ``"ModuleNotFoundError"`` error. You should update the import statements in the example notebooks and test scripts to reflect the new package directory name.

#### Updating package root directory from 'src/simulai' to 'simulai

* The ``setup_tools/find_packages()`` function is used to automatically find all packages in the package directory. Therefore, if the base directory ``src/simulai`` is updated to ``simulai``, it is likely that there will be no problem. 

#### Removing 'src' folder for package structure consistency
* @Joao-L-S-Almeida  I suggest removing the 'src' folder in the package structure to maintain consistency and eliminate unnecessary levels of nesting. However, if this change is not in line with current development plans or the 'src' will be kept, you can closed this pull request. I can update the documentation and create a new pull request if needed.

**Comment by Joao-L-S-Almeida** [comment]
All right, @TarikKaanKoc. I will execute the following procedure. 
* Merging your updates to the most recent modifications in `main.` 
* Executing  some sanity checks.
* Upgrading the package to 0.99.8.

**Comment by TarikKaanKoc** [comment]
> All right, @TarikKaanKoc. I will execute the following procedure.
> 
> * Merging your updates to the most recent modifications in `main.`
> * Executing  some sanity checks.
> * Upgrading the package to 0.99.8.

I updated the logo, don't forget to rearrange it : https://github.com/IBM/simulai/issues/47#issuecomment-1398317971

**Comment by TarikKaanKoc** [comment]
Image description

**Comment by Joao-L-S-Almeida** [comment]
I did the modifications aforementioned. 
I this [commit](https://github.com/IBM/simulai/commit/29cb36051a55e1f98639dcf1eaeab7c43b541487) I modified pyproject.toml in order to generate the package for PyPI. Maybe it could not be the best way to do it. Please, give a look.

**Pull request merged**
